# Generated by Django 3.0.5 on 2020-09-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200909_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='headline',
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
