# Generated by Django 3.0.5 on 2020-09-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20200910_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='client',
            name='company_website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
