# Generated by Django 3.0 on 2020-02-08 21:14

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('short_description', models.TextField(help_text='Max characters: 500', max_length=500, null=True)),
                ('long_description', tinymce.models.HTMLField(default='Lorem Ipsum')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('call_to_action', models.CharField(choices=[('Sell', (('Order Now', 'Order Now'), ('Hire Zack', 'Hire Zack'), ('Hire My Team', 'Hire My Team'), ('Book a Call', 'Book a Call'), ('Get Training', 'Get Training'))), ('Contact', (('Contact Us', 'Contact Us'), ('Get Help Now', 'Get Help Now'), ('Get in Touch', 'Get in Touch')))], default='Order Now', max_length=30)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
    ]
