# Generated by Django 3.0 on 2020-03-09 20:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, default='Lorem Ipsum', null=True),
        ),
    ]
