# Generated by Django 3.0 on 2020-02-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='display',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
