# Generated by Django 3.0 on 2019-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
