# Generated by Django 3.0 on 2020-03-09 20:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200309_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
