# Generated by Django 3.0 on 2019-12-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='show',
            new_name='display',
        ),
    ]
