# Generated by Django 3.0 on 2020-01-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191231_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='call_to_action',
            field=models.CharField(choices=[('Order Now', 'Order Now'), ('Contact Us', 'Contact Us'), ('Get Training', 'Get Training'), ('Book a Call', 'Book a Call')], default='Order Now', max_length=30),
        ),
    ]
