# Generated by Django 3.0 on 2020-01-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_call_to_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='call_to_action',
            field=models.CharField(choices=[('Order Now', 'Order Now'), ('Contact', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Book a Call', 'Book a Call'), ('Contact Us', 'Contact Us'), ('Get Training', 'Get Training'), ('Get Help Now', 'Get Help Now'), ('Get in Touch', 'Get in Touch')], default='Order Now', max_length=30),
        ),
    ]
