# Generated by Django 3.0 on 2020-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20200103_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='call_to_action',
            field=models.CharField(choices=[('Sell', (('Order Now', 'Order Now'), ('Hire Zack', 'Hire Zack'), ('Hire My Team', 'Hire My Team'), ('Book a Call', 'Book a Call'), ('Get Training', 'Get Training'))), ('Contact', (('Contact Us', 'Contact Us'), ('Get Help Now', 'Get Help Now'), ('Get in Touch', 'Get in Touch')))], default='Order Now', max_length=30),
        ),
    ]
