# Generated by Django 3.0 on 2020-01-03 11:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200103_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=tinymce.models.HTMLField(default='Lorem Ipsum'),
        ),
    ]
