# Generated by Django 3.0.5 on 2020-09-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20200910_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
