# Generated by Django 3.0.5 on 2020-09-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20200910_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled')], default='', max_length=50),
        ),
    ]
