# Generated by Django 3.0.5 on 2020-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20200910_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
