# Generated by Django 3.1 on 2020-09-15 14:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20200911_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-date']},
        ),
        migrations.AlterField(
            model_name='service',
            name='long_description',
            field=tinymce.models.HTMLField(default='', help_text='Long description (optional)'),
        ),
    ]
