# Generated by Django 3.1.2 on 2020-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20201008_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='companies', to='services.Client'),
        ),
    ]
