# Generated by Django 3.1.2 on 2020-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20201016_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='worked_with',
            field=models.BooleanField(default=False),
        ),
    ]
