# Generated by Django 3.0.5 on 2020-08-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='You can only choose 1 tag per post.', null=True, related_name='posts', to='blog.Tag'),
        ),
    ]
