# Generated by Django 3.1.2 on 2020-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20201008_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='author status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='client status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_contact',
            field=models.BooleanField(default=False, verbose_name='contact status'),
        ),
    ]
