# Generated by Django 3.0.5 on 2020-09-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
