# Generated by Django 3.1.2 on 2020-10-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
