# Generated by Django 3.0 on 2020-02-06 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200206_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
