# Generated by Django 4.0.1 on 2022-02-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='review_source_logos/')),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='author_name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_image',
        ),
        migrations.AddField(
            model_name='review',
            name='customer_credential',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='portfolio.reviewsource'),
        ),
    ]
