# Generated by Django 3.0.5 on 2020-09-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_repository',
            field=models.URLField(blank=True, help_text="Link to your project's github repository (if applicable).", null=True, verbose_name='github repo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', 'Idea'), ('planning', 'Planning'), ('designing', 'Designing'), ('building', 'Building'), ('almost done', 'Almost Done'), ('complete', 'Complete')], default='idea', max_length=50),
        ),
    ]
