# Generated by Django 3.0.5 on 2020-09-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200910_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', help_text='Maximum 100 characters.', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
