# Generated by Django 4.0.1 on 2022-02-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_reviewsource_rename_author_name_review_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsource',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='review_source_logos/'),
        ),
    ]
