# Generated by Django 4.0.1 on 2022-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_review_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='action_url',
            field=models.URLField(blank=True, help_text='The url you want the offer to go to after being clicked on.', null=True),
        ),
    ]
