# Generated by Django 4.0.1 on 2022-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_featured_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Concept', 'Concept')], max_length=50),
        ),
    ]
