# Generated by Django 3.1.2 on 2020-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200910_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='future_plans',
        ),
        migrations.RemoveField(
            model_name='project',
            name='how_it_works',
        ),
        migrations.RemoveField(
            model_name='project',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
