# Generated by Django 4.0.1 on 2022-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Live', 'Live'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Concept', 'Concept')], max_length=50),
        ),
    ]
