# Generated by Django 4.0.1 on 2022-11-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_offer_action_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='short_description',
            new_name='sales_copy',
        ),
    ]
