# Generated by Django 4.0.1 on 2022-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_short_description_offer_sales_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
