# Generated by Django 4.0.1 on 2022-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Collaborator', 'Collaborator')], default='Owner', max_length=50),
        ),
    ]
