# Generated by Django 4.0.1 on 2022-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_collaborators_project_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='collaborators',
            new_name='contributors',
        ),
    ]
