# Generated by Django 4.0.1 on 2022-02-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_collaborators_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.image')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, to='portfolio.Contributor'),
        ),
    ]
