# Generated by Django 4.0.1 on 2022-02-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_technology_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='role',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Prototype', 'Prototype'), ('Live', 'Live'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Paused', 'Paused'), ('Concept', 'Concept')], max_length=50),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Collaborator', 'Collaborator'), ('Partner', 'Partner'), ('Lead Developer', 'Lead Developer')], default='Collaborator', max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='portfolio.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='portfolio.project')),
            ],
        ),
    ]
