# Generated by Django 4.0.1 on 2022-02-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_project_role_alter_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributors',
        ),
    ]
