# Generated by Django 4.0.1 on 2022-02-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
