# Generated by Django 3.0.5 on 2020-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200910_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Value',
        ),
    ]
