# Generated by Django 3.0.5 on 2020-09-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
