# Generated by Django 3.1 on 2020-09-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200914_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
