# Generated by Django 3.1.2 on 2020-10-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200914_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='https://via.placeholder.com/400', upload_to='profile_pictures/'),
        ),
    ]
