# Generated by Django 3.1.2 on 2020-10-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201008_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
